spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nms?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&charset=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      # password: 123456     # 如果有密码，取消注释
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  application:
    name: novle-server

server:
  port: 5240


minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: nms-manage

#配置plus答应sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 开启驼峰命名转换
  mapper-locations: classpath:/mapper/*.xml

#设置日志级别，ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: info


# 默认小说封面地址、默认作者头像地址、默认用户头像地址
default:
  authorAvatarUrl: https://nms.oss-cn-beijing.aliyuncs.com/authorAvatar/default.png
  visitorAvatarUrl:  https://nms.oss-cn-beijing.aliyuncs.com/visitorAvatar/default.png
  novelCoverUrl: https://nms.oss-cn-beijing.aliyuncs.com/novelCover/default.png
  managerAvatarUrl: https://nms.oss-cn-beijing.aliyuncs.com/managerAvatar/default.png