server:
  port: 5220
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: common-server

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        username: nacos
        password: 123456
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        username: nacos
        password: 123456
        file-extension: yml
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 10000
            read-timeout: 30000
      circuitbreaker:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

  main:
    allow-bean-definition-overriding: true

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  # 数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nms?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&charset=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: ${QQ_mail}
    password: ${QQ_SMTP/IMAP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml

#设置日志级别
logging:
  level:
    root: info

# minio 配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: nms
