server:
  port: 5220
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: common-server
  
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB        # 单个文件最大大小
      max-request-size: 20MB     # 整个请求最大大小
  
  # 数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nms?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&charset=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # 邮件配置
  mail:
    host: smtp.qq.com                    # QQ邮箱SMTP服务器
    port: 587                            # 端口
    username: 2531215075@qq.com          # 发送方邮箱
    password: ${QQ_SMTP/IMAP}            # SMTP授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml

#设置日志级别，ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: info

# minio 配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: nms

# 默认小说封面地址、默认作者头像地址、默认用户头像地址
default:
  authorAvatarUrl: http://127.0.0.1:9000/nms/AUTHOR_AVATAR/5c347d6e-8d91-496f-857d-af9b45cdb480.jpg
  visitorAvatarUrl:  http://127.0.0.1:9000/nms/VISITOR_AVATAR/ea59d798-2f32-43b8-bd96-cb70d9b9d054.jpg
  novelCoverUrl: http://127.0.0.1:9000/nms/NOVEL_COVER/88e08331-0134-43f3-ae66-1f81c4ca191e.jpg
  managerAvatarUrl: http://127.0.0.1:9000/nms/MANAGER_AVATAR/5bdfcbb8-9b29-4c2d-873a-6a4539714653.jpg

